### ISSUE TITLE
Conjuntos Numéricos

### ISSUE THREAD

**Issue by JoseRodriguez-23620213** [SistemasTecTlaxiaco/actividad-4-mapa-mental-JoseRodriguez-23620213#2]
![Mapa numerico](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-JoseRodriguez-23620213/assets/143229717/00a28b60-5929-4f12-af8d-6e70a1939a2a)

**Comment by josealfredo79** [comment]
Favor de estructurar

**Comment by Mari-00** [comment]
Manejo conceptual y dominio del tema: 10%
Relación entre los conceptos incluidos en el mapa: 19%
Calidad de la presentación: 14%
Jerarquía: 17%
promedio final: 12%
Evaluado por el equipo 5

**Comment by josealfredo79** [comment]
Les comente que estructurar como un mapa menta...lo anterior es mas un mapa jerárquico...
